"""SQLAlchemy ORM model for the paper_embeddings table.

Stores vector embeddings generated by sentence-transformers for
semantic search via pgvector.
"""

from sqlalchemy import ForeignKey, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship

from pgvector.sqlalchemy import Vector

from app.models.base import Base

# Embedding dimension for all-MiniLM-L6-v2
EMBEDDING_DIM = 384


class PaperEmbedding(Base):
    """Stores the vector embedding for a single paper."""

    __tablename__ = "paper_embeddings"

    paper_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("papers.id", ondelete="CASCADE"),
        primary_key=True,
    )
    embedding = mapped_column(Vector(EMBEDDING_DIM))

    # ── Relationships ─────────────────────────────────────────────────────
    paper: Mapped["PaperORM"] = relationship(
        "PaperORM", back_populates="embedding",
    )

    def __repr__(self) -> str:
        return f"<PaperEmbedding paper_id={self.paper_id}>"
