"""Add photo fields and generated_images table

Revision ID: 31d6564a20af
Revises: 0001
Create Date: 2026-08-01 22:56:30.828692
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d6564a20af'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment="'analytics' or 'recognition'"),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('photo_url', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('photo_public_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'photo_public_id')
    op.drop_column('students', 'photo_url')
    op.drop_table('generated_images')
    # ### end Alembic commands ###
